--- 
development: 
  adapter: mysql
  username: distanced
  host: localhost
  database: distance_development
  password: kNJwDBLkTtPixpTcbPy0gs1LT
production: 
  adapter: mysql
  username: distancep
  host: localhost
  database: distance_production
  password: 9GTIGoWNrmcTh0WbRr0mtsSuY
test: 
  adapter: mysql
  username: distancet
  host: localhost
  database: distance_test
  password: Pk8Z6LghoHmFTrlXuBFSKA7ak
